apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api            # renamed to be descriptive and lowercase
  namespace: three-tier
  labels:
    role: backend
    env: demo
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: backend
  template:
    metadata:
      labels:
        role: backend
    spec:
      imagePullSecrets:
        - name: ecr-secret       # must match the secret you created in kubectl
      containers:
        - name: backend
          image: 407622020962.dkr.ecr.us-east-1.amazonaws.com/backend:2
          imagePullPolicy: Always
          env:
            - name: MONGO_CONN_STR
              value: mongodb://mongodb-svc:27017/todo?directConnection=true
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-sec
                  key: username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-sec
                  key: password
          ports:
            - containerPort: 3500
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3500
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 3500
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
          startupProbe:
            httpGet:
              path: /started
              port: 3500
            initialDelaySeconds: 0
            periodSeconds: 10
            failureThreshold: 30
